# Generated by Django 6.0.4 on 2026-04-10 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['-date', 'start_time'], 'verbose_name': 'Смена', 'verbose_name_plural': 'Смены'},
        ),
    ]
