# Generated by Django 6.0.4 on 2026-04-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_shift_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkloadRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('required', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Нагрузка',
                'verbose_name_plural': 'Нагрузка',
                'ordering': ['weekday', 'start_time'],
            },
        ),
    ]
