# Generated by Django 6.0.4 on 2026-04-10 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_workloadrequirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWorkloadRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('required', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Нагрузка (дата)',
                'verbose_name_plural': 'Нагрузка (даты)',
                'ordering': ['date', 'start_time'],
                'indexes': [models.Index(fields=['date'], name='daily_workload_date_idx')],
            },
        ),
    ]
