# Generated by Django 6.0.4 on 2026-04-10 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_dailyworkloadrequirement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('status', models.CharField(choices=[('open', 'Открыт'), ('approved', 'Одобрен'), ('rejected', 'Отклонён')], default='open', max_length=16, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Запрос на изменение',
                'verbose_name_plural': 'Запросы на изменение',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='change_request_status_idx'), models.Index(fields=['employee', 'created_at'], name='change_request_employee_idx')],
            },
        ),
    ]
